name: Run tests

on: [pull_request, push]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        name-prefix: ['']
        os: [ubuntu-latest]
        python: [3.7, 3.8, 3.9, '3.10', 3.11, pypy-3.9]
        include:
          # To keep the overall number of runs low, we test Windows
          # only on the latest CPython.
          - name-prefix: 'win-'
            os: windows-latest
            python: 3.11

    name: ${{ format('{0}{1}', matrix.name-prefix, matrix.python) }}
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color
        # This is needed to avoid a terminfo-related crash when
        # testing PyPy.
      PYTHONPATH: .

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - run: pip install . && rm -r hy
        # We want to be sure we're testing the installed version,
        # instead of running from the source tree.
    - run: pip install pytest
    - run: pytest
