name: Tests

on: [pull_request, push]

jobs:

  pytest:
    # Run the test suite.

    strategy:
      fail-fast: false
      matrix:
        name-prefix: ['']
        os: [ubuntu-latest]
        python: [3.9, '3.10', 3.11, 3.12, 3.13, 3.14, pypy-3.11]
        include:
          # To keep the overall number of runs low, we test Windows and MacOS
          # only on the latest CPython.
          - name-prefix: 'win-'
            os: windows-latest
            python: 3.14
          - name-prefix: 'mac-'
            os: macos-latest
            python: 3.14

    name: ${{ matrix.name-prefix }}${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color
        # This is needed to avoid a terminfo-related crash when
        # testing PyPy.
      PYTHONPATH: .

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python }}
    - name: Install
      shell: bash
      run: |
        pip install .
        rm -r hy
          # We want to be sure we're testing the installed version,
          # instead of running from the source tree.
        pip install 'pytest >= 8.4.1'
    - name: Test
      shell: bash
      run: python -m pytest tests

  docs:
    # Try building the manual, ensuring that Sphinx doesn't produce
    # any warnings.

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: 3}
    - name: Install
      run: |
        pip install .
        pip install -r docs/requirements.txt
    - run: sphinx-build -W -b html docs/ docs/_build/
