name: Tests

on: [pull_request, push]

jobs:

  pytest:
    # Run the test suite.

    strategy:
      fail-fast: false
      matrix:
        name-prefix: ['']
        os: [ubuntu-latest]
        python: [3.8, 3.9, '3.10', 3.11, 3.12, 3.13-dev, pypy-3.10, pyodide]
        include:
          # To keep the overall number of runs low, we test Windows and MacOS
          # only on the latest CPython.
          - name-prefix: 'win-'
            os: windows-latest
            python: 3.12
          - name-prefix: 'mac-'
            os: macos-latest
            python: 3.12

    name: ${{ format('{0}{1}', matrix.name-prefix, matrix.python) }}
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color
        # This is needed to avoid a terminfo-related crash when
        # testing PyPy.
      PYTHONPATH: .

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - if: ${{ matrix.python != 'pyodide' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - if: ${{ matrix.python == 'pyodide' }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - if: ${{ matrix.python == 'pyodide' }}
      uses: actions/setup-node@v4
    - name: Install
      shell: bash
      run: |
        if [[ ${{ matrix.python }} = pyodide ]] ; then
            npm install pyodide
            pip install pyodide-build
            pyodide venv .venv-pyodide
            source .venv-pyodide/bin/activate
        fi
        pip install .
        rm -r hy
          # We want to be sure we're testing the installed version,
          # instead of running from the source tree.
        pip install pytest
    - name: Test
      shell: bash
      run: |
        if [[ ${{ matrix.python }} = pyodide ]] ; then
            source .venv-pyodide/bin/activate
        fi
        python -m pytest tests

  docs:
    # Try building the manual, ensuring that Sphinx doesn't produce
    # any warnings.

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: 3}
    - name: Install
      run: |
        pip install .
        pip install -r requirements-dev.txt
    - run: sphinx-build -W -b html docs/ docs/_build/
